### PR TITLE
Add numpad and tmux layout

### PR DESCRIPTION
**Pull request by Drudoo**
Two new layouts for a numpad and a tmux navigator.

### Numpad

Regular layout
```text
┌╌╌╌╌┐  ╔════╗  ╔════╗  ╔════╗
┊ 11 ┊  ║  8 ║  ║  5 ║  ║  2 ║
└╌╌╌╌┘  ╚════╝  ╚════╝  ╚════╝
           9       8       7
╔════╗  ╔════╗  ╔════╗  ╔════╗
║ 10 ║  ║  7 ║  ║  4 ║  ║  1 ║
╚════╝  ╚════╝  ╚════╝  ╚════╝
   0       6       5       4
╔════╗  ╔════╗  ╔════╗  ╔════╗
║  9 ║  ║  6 ║  ║  3 ║  ║  0 ║
╚════╝  ╚════╝  ╚════╝  ╚════╝
 enter     3       2       1
```
Shirt layout
```text
┌╌╌╌╌┐  ╔════╗  ╔════╗  ╔════╗
┊ 11 ┊  ║  8 ║  ║  5 ║  ║  2 ║
└╌╌╌╌┘  ╚════╝  ╚════╝  ╚════╝
           +       -       =
╔════╗  ╔════╗  ╔════╗  ╔════╗
║ 10 ║  ║  7 ║  ║  4 ║  ║  1 ║
╚════╝  ╚════╝  ╚════╝  ╚════╝
   .       /       %       $
╔════╗  ╔════╗  ╔════╗  ╔════╗
║  9 ║  ║  6 ║  ║  3 ║  ║  0 ║
╚════╝  ╚════╝  ╚════╝  ╚════╝
   ,   backspace delete   ESC
```

### Tmux

Regular layout
```text
┌╌╌╌╌┐  ╔════╗  ╔════╗  ╔════╗
┊ 11 ┊  ║  8 ║  ║  5 ║  ║  2 ║
└╌╌╌╌┘  ╚════╝  ╚════╝  ╚════╝
        split v  move l move r
╔════╗  ╔════╗  ╔════╗  ╔════╗
║ 10 ║  ║  7 ║  ║  4 ║  ║  1 ║
╚════╝  ╚════╝  ╚════╝  ╚════╝
split h new window      move u
╔════╗  ╔════╗  ╔════╗  ╔════╗
║  9 ║  ║  6 ║  ║  3 ║  ║  0 ║
╚════╝  ╚════╝  ╚════╝  ╚════╝
exit    cycle p cycle n move d
```

### CODE REVIEW

**Comment by thediveo** [comment]
Thank you for your contribution! This looks quite interesting, and you make me considering tmux in earnest when messing with my Kubernetes clusters in a jumphost terminal session!

I have two questions regarding your PR:
- can you please place your PR against the `develop` branch instead of against `master`? (note to self: document this) Unfortunately, GitHub doesn't allow me to change this, only the owner of the PR can do this. The `develop` branch now has an updated local-env lua setup, and adapted build and linting; also, I'm using `git flow` with its branching model to manage the multibow repo.
- what is the reason for the number keypad to horizontally mirrored with respect to the number pad of PC keyboards?

**Comment by Drudoo** [comment]
My regular workflow is tmux, vim and i3, so my plan is to make layouts for those. Tmux was just a quick test, as I got my keybow on friday. It seems to work great and I might add a shift layout with resizing.

1. Yes of course. 
2. When the keybow is lying next to my keyboard, the cord just comes out between key 8 and 5, so it makes sense to have the layout like that. It's a bit weird at first, but having the cord go to the left or right would be weirder.

**Comment by thediveo** [comment]
That's the standard "portrait" layout, I'm also assuming for the stable keybow layouts. But then according to your documentation the top row is _987, when a standard PC keymap layout is _789. That's the reason why I'm asking; I would suspect that users would expect standard PC keymap layout, or am I mistaken here?

**Comment by thediveo** [comment]
Please allow me some time to set up a CLA, so contributions are handled in a defined manner. The gist will probably be that the PRs need to be MIT.

**Comment by Drudoo** [comment]
Oh i see now. I don't have a numpad on my homekeyboard as it is 60% but i just checked my work keyboard and you are right, i reversed the numbers. I will update the files in my repo to the standard 

```text
┌╌╌╌╌┐  ╔════╗  ╔════╗  ╔════╗
┊ 11 ┊  ║  8 ║  ║  5 ║  ║  2 ║
└╌╌╌╌┘  ╚════╝  ╚════╝  ╚════╝
           7       8       9
╔════╗  ╔════╗  ╔════╗  ╔════╗
║ 10 ║  ║  7 ║  ║  4 ║  ║  1 ║
╚════╝  ╚════╝  ╚════╝  ╚════╝
   0       4       5       6
╔════╗  ╔════╗  ╔════╗  ╔════╗
║  9 ║  ║  6 ║  ║  3 ║  ║  0 ║
╚════╝  ╚════╝  ╚════╝  ╚════╝
 enter     1       2       3
```

That's fine. My PR can wait 👍

**Comment by thediveo** [comment]
project is archived

**Pull request closed without merging**
